### ISSUE TITLE
Error passing NC files

### ISSUE THREAD

**Issue by dergrunepunkt** [winder/builds#1]
I detected that gcodesender produces an error when parses the here attached.

This line in the file, for example:
`G02 X107.461929 Y69.408606 Z-1.000000 I19.167338 J12.058391`

gives this error:

> An error was detecting sending '7.461929Y69.408606Z-1.000000I19.167338J12.058391' error: Expected command letter

Cheers!
[Balsa test_0022.nc.txt](https://github.com/winder/builds/files/393806/Balsa.test_0022.nc.txt)

**Comment by winder** [comment]
This file seems to work using the UGS nightly build. Please try v1.0.9 and the nightly build. If those aren't working you can open a bug report here: https://github.com/winder/Universal-G-Code-Sender/issues

**Comment by dergrunepunkt** [comment]
Using 1.0.9 works fine, I open a ticket because the message I get when I open the nightly build using the "UGS Platform" build I downloaded two days ago, you can ignore my report if you want, I did my part.
